# Configuration override pour les mots de passe
# Généré automatiquement par setup.sh

version: '3.8'

services:
  postgres-clients:
    environment:
      - POSTGRES_PASSWORD=iGOzc2ZjHYE3iyvnZ61lv8pYVMcPJ8Cqwp8CxK9

  postgres-tickets:
    environment:
      - POSTGRES_PASSWORD=iGOzc2ZjHYE3iyvnZ61lv8pYVMcPJ8Cqwp8CxK9

  grafana:
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=4jbnmMIEZPcdFScfetU304DaJFrubYSpeeyHfi9

  prometheus:
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
